[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }


# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[language-server.rust-analyzer.config.check]
command = "clippy"


# Web
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/opt/homebrew/lib/node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
language-servers = [ "astro-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = [ "--parser", "astro", "--plugin", "prettier-plugin-astro" ] }
auto-format = true

[language-server.emmet-ls]
command = "emmet-ls"
args = [ "--stdio" ]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "emmet-ls"]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "emmet-ls"]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true
